config/routes.rb
Miniapp::Application.routes.draw do
  devise_for :users
  
  resources :users do
    resources :task_lists do
      resources :tasks 
    end
    post :mark_task_list_as_favorite
    post :unmark_task_list_as_favorite
    collection do
      get :home
    end
  end
  
  resources :task_lists, only: [:index]

  root to: "users#home"

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_list
  attr_accessible :name, :task_list, :task_list_id
  validates_presence_of :name, :task_list
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  belongs_to :user                             
  attr_accessible :name, :privacy, :user_id
  validates_presence_of :name, :privacy, :user
  has_many :tasks
  
  scope :public, where(privacy: "public")
  
  def public?
    privacy == "public"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :task_lists
  has_and_belongs_to_many :favorite_task_lists, class_name: "TaskList"
  
  def mark_task_list_as_favorite(task_list)
    favorite_task_lists << task_list
    save
  end
  
  def unmark_task_list_as_favorite(task_list)
    favorite_task_lists.delete task_list
    save
  end
  
  def task_list_marked_as_favorite?(task_list)
    favorite_task_lists.include?(task_list)
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html,:js

  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_filter :fetch_user
  
  def index
    @task_lists = TaskList.public
    respond_with(@task_lists)
  end

  def show
    @task_list = TaskList.find(params[:id])
    respond_with(@user, @task_list)
  end

  def new
    @task_list = TaskList.new
    respond_with(@task_list)
  end

  def edit
    @task_list = TaskList.find(params[:id])
  end

  def create
    @task_list = TaskList.new(params[:task_list])
    @task_list.save
    respond_with(@user, @task_list)
  end

  def update
    @task_list = TaskList.find(params[:id])
    @task_list.update_attributes(params[:task_list])
    respond_with(@user, @task_list)
  end

  def destroy
    @task_list = TaskList.find(params[:id])
    @task_list.destroy
    respond_with(@user, @task_list)
  end
  
  private
    def fetch_user
      @user = params[:user_id] ? User.find(params[:user_id]) : current_user
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :fetch_task_list
  
  def index
    @tasks = Task.all
    respond_with(@tasks)
  end

  def show
    @task = Task.find(params[:id])
    respond_with(@task)
  end

  def new
    @task = Task.new
    respond_with(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(params[:task])
    if @task.save
      respond_with(@task_list.user, @task_list)
    else
      respond_with(@task)
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      respond_with(@task_list.user, @task_list)
    else
      @task.destroy if @task.name.empty?
      respond_with(@task)
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_with(@task_list.user, @task_list)
  end
  
  private
    def fetch_task_list
      @task_list = TaskList.find(params[:task_list_id])
    end   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_filter :fetch_user, except: [:home]
  before_filter :fetch_task_list, only: [:mark_task_list_as_favorite, :unmark_task_list_as_favorite]

  def home
    @user = current_user
    @task_list = @user.task_lists.first
  end
  
  def mark_task_list_as_favorite
    @user.mark_task_list_as_favorite(@task_list)
    respond_with(@task_list.user, @task_list)
  end
  
  def unmark_task_list_as_favorite
    @user.unmark_task_list_as_favorite(@task_list)
    respond_with(@task_list.user, @task_list)
  end  
  
  private
    def fetch_user
      @user = User.find(params[:user_id])
    end
    
    def fetch_task_list
      @task_list = TaskList.find(params[:task_list_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Miniapp
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    
  %body
    #wrapper  
      #header
        %h1= link_to "Mini To Do", home_users_path
        #navigation
          = link_to "Find Lists", task_lists_path
          = link_to t(:sign_out), destroy_user_session_path, method: :delete
      
      - if user_signed_in?
        #lists_navigation
          %h3= "Your Lists" 
          #new_task_list= link_to image_tag("add.png", alt: "new_task_list", title: "new_task_list"), [:new, current_user, :task_list]
          #user_task_lists= render current_user.task_lists

          %h3= "Your Favorites"
          #favorite_task_lists= render current_user.favorite_task_lists
    
      #content= yield   
     
      #footer

app/views/task_lists/_form.html.haml
= simple_form_for([@user, @task_list]) do |f|
  = f.error_notification
  = f.hidden_field :user_id, value: @user.id

  .form-inputs
    = f.input :name
    = f.input :privacy, collection: [[t(:private), "private"], [t(:public), "public"]], as: :radio_buttons, checked: "private"

  .form-actions
    = f.button :submit

:javascript
  $("#task_list_name").focus()

app/views/task_lists/_task_list.html.haml
.task_list
  = link_to truncate(task_list.name, length: 20), [task_list.user, task_list], class: "task_list_name"
  
  - if task_list.user == current_user
    .task_list_actions{style: "display: none"}
      = link_to image_tag("edit.png", title: "edit", alt: "edit"), [:edit, task_list.user, task_list]
      = link_to image_tag("trash.png", title: "remove", alt: "remove"), [task_list.user, task_list], method: :delete, data: { confirm: 'Are you sure?' }
      
  

app/views/task_lists/edit.html.haml
%h1 Editing List

= render 'form'

= link_to 'Back', [@user, :task_lists]

app/views/task_lists/index.html.haml
#find_task_lists
  %h1 Find Lists

  #task_lists= render @task_lists

app/views/task_lists/new.html.haml
%h1 New List

= render 'form'

= link_to 'Back', [@user, :task_lists]

app/views/task_lists/show.html.haml
#task_list
  %h1
    = link_to @task_list.name
    = image_tag("#{@task_list.privacy}.png", title: @task_list.privacy, alt: @task_list.privacy)
    
  - if @user == current_user
    = link_to 'edit', [:edit, @task_list.user, @task_list], id: "task_list_edit"

  - if @user != current_user
    #task_list_owner
      = "created by: "
      = link_to @user.email, [@user, :task_lists]
  
  #actions
    - if @user == current_user  
      = link_to_function "New Task", "$('#task_name').focus();"
    - elsif @task_list.public?
      - if current_user.task_list_marked_as_favorite?(@task_list)    
        = link_to "Unmark as favorite", user_unmark_task_list_as_favorite_path(current_user, task_list_id: @task_list.id), method: :post
      - else
        = link_to "Mark as favorite", user_mark_task_list_as_favorite_path(current_user, task_list_id: @task_list.id), method: :post         
    = link_to 'Back', [@task_list.user, :task_lists]

  #tasks
    = render @task_list.tasks
    - if @task_list.user == current_user
      = render "tasks/form", task_list: @task_list, task: Task.new

app/views/tasks/_form.html.haml
= simple_form_for([task_list.user, task_list, task], remote: true) do |f|
  = f.hidden_field :task_list_id, value: task_list.id
  = f.input :name, label: false, placeholder: "New task"
    
:javascript
  $("#task_name").focus();

app/views/tasks/_task.html.haml
.task{id: "task_#{task.id}", class: "#{task.task_list.user == current_user ? 'owner' : 'visiting' }", "data-edit-url" => edit_user_task_list_task_path(task.task_list.user, task.task_list, task, format: :js)}
  .task_name= task.name
  
  - if task.task_list.user == current_user
    .task_actions{style: "display: none"}
      = link_to image_tag("edit.png", title: "edit", alt: "edit"), [:edit, task.task_list.user, task.task_list, task], remote: true
      = link_to image_tag("trash.png", title: "remove", alt: "remove"), [task.task_list.user, task.task_list, task], method: :delete, data: { confirm: 'Are you sure?' }, remote: true

app/views/tasks/create.js.erb
$("#new_task").before("<%= escape_javascript(render partial: 'task', locals: {task: @task}) %>");
$("#task_name").val("").focus();

app/views/tasks/destroy.js.erb
$("#task_<%= @task.id %>").fadeOut();

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form', task_list: @task_list, task: @task

= link_to 'Back', [@task_list.user, @task_list] 

app/views/tasks/edit.js.erb
$("#task_<%= @task.id %>").html(" <%= escape_javascript(render partial: 'tasks/form', locals: {task_list: @task_list, task: @task}) %>");
$("#edit_task_<%= @task.id %> #task_name").focus();

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %tr
    %th Name
    %th Task list
    %th
    %th
    %th

  - @tasks.each do |task|
    %tr
      %td= task.name
      %td= task.task_list
      %td= link_to 'Show', task
      %td= link_to 'Edit', edit_task_path(task)
      %td= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form', task_list: @task_list, task: @task

= link_to 'Back', [@task_list.user, @task_list]

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @task.name
%p
  %b Task list:
  = @task.task_list

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path

app/views/tasks/update.js.erb
<% if @task.name.present? %>
	$("#task_<%= @task.id %>").replaceWith("<%= escape_javascript(render partial: 'task', locals: {task: @task}) %>")
<% else %>
	$("#task_<%= @task.id %>").remove();
<% end %>

app/views/users/home.html.haml
#home
  - if @task_list.nil?
    = "You don't have any created lists."
    = link_to "Create one.", [:new, current_user, :task_list]
  - else
    = render file: "task_lists/show"